// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Remoni.API.DataAccess.Client
{
    using Models;

    /// <summary>
    /// The ReMoni API provides account related data and management options
    /// using HTTP requests. The API attempts to conform to the design
    /// principles of Representational State Transfer (REST) and is using
    /// JSON data format for request- and response payload. This document is
    /// intended for developers with basic REST knockledge
    /// </summary>
    public partial interface IRemoniAPIClient : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        Newtonsoft.Json.JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        Newtonsoft.Json.JsonSerializerSettings DeserializationSettings { get; }


        /// <summary>
        /// Gets the IAccounts.
        /// </summary>
        IAccounts Accounts { get; }

        /// <summary>
        /// Gets the IAlarmGroups.
        /// </summary>
        IAlarmGroups AlarmGroups { get; }

        /// <summary>
        /// Gets the IAlarms.
        /// </summary>
        IAlarms Alarms { get; }

        /// <summary>
        /// Gets the IAlarmTypes.
        /// </summary>
        IAlarmTypes AlarmTypes { get; }

        /// <summary>
        /// Gets the IAlarmUserNotes.
        /// </summary>
        IAlarmUserNotes AlarmUserNotes { get; }

        /// <summary>
        /// Gets the IData.
        /// </summary>
        IData Data { get; }

        /// <summary>
        /// Gets the IDataTypes.
        /// </summary>
        IDataTypes DataTypes { get; }

        /// <summary>
        /// Gets the IGateways.
        /// </summary>
        IGateways Gateways { get; }

        /// <summary>
        /// Gets the IRoles.
        /// </summary>
        IRoles Roles { get; }

        /// <summary>
        /// Gets the ISensors.
        /// </summary>
        ISensors Sensors { get; }

        /// <summary>
        /// Gets the ITags.
        /// </summary>
        ITags Tags { get; }

        /// <summary>
        /// Gets the IUnits.
        /// </summary>
        IUnits Units { get; }

        /// <summary>
        /// Gets the IUnitTypes.
        /// </summary>
        IUnitTypes UnitTypes { get; }

        /// <summary>
        /// Gets the IUsers.
        /// </summary>
        IUsers Users { get; }

    }
}
