// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Remoni.API.DataAccess.Client.Models
{
    using System.Linq;

    public partial class AlarmSolutionNoRefDto
    {
        /// <summary>
        /// Initializes a new instance of the AlarmSolutionNoRefDto class.
        /// </summary>
        public AlarmSolutionNoRefDto() { }

        /// <summary>
        /// Initializes a new instance of the AlarmSolutionNoRefDto class.
        /// </summary>
        public AlarmSolutionNoRefDto(int alarmSolutionId, string description = default(string))
        {
            AlarmSolutionId = alarmSolutionId;
            Description = description;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "AlarmSolutionId")]
        public int AlarmSolutionId { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Description")]
        public string Description { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
