// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Remoni.API.DataAccess.Client.Models
{
    using System.Linq;

    public partial class ArrayProperty
    {
        /// <summary>
        /// Initializes a new instance of the ArrayProperty class.
        /// </summary>
        public ArrayProperty() { }

        /// <summary>
        /// Initializes a new instance of the ArrayProperty class.
        /// </summary>
        public ArrayProperty(string name, ArrayProperty property = default(ArrayProperty), int? index = default(int?))
        {
            Property = property;
            Name = name;
            Index = index;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Property")]
        public ArrayProperty Property { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Index")]
        public int? Index { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Name");
            }
            if (this.Property != null)
            {
                this.Property.Validate();
            }
        }
    }
}
