// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Remoni.API.DataAccess.Client.Models
{
    using System.Linq;

    public partial class CreateUnitDto
    {
        /// <summary>
        /// Initializes a new instance of the CreateUnitDto class.
        /// </summary>
        public CreateUnitDto() { }

        /// <summary>
        /// Initializes a new instance of the CreateUnitDto class.
        /// </summary>
        /// <param name="dataInterval">Possible values include: 'Minute',
        /// 'Minutes5', 'Seconds20Boost'</param>
        public CreateUnitDto(string dataInterval, string name = default(string), string description = default(string), double? latitude = default(double?), double? longitude = default(double?), double? gpsAccuracy = default(double?), System.Collections.Generic.IList<WriteUnitValueDto> unitValues = default(System.Collections.Generic.IList<WriteUnitValueDto>), AccountIdDto account = default(AccountIdDto), UnitTypeIdDto unitType = default(UnitTypeIdDto))
        {
            Name = name;
            Description = description;
            Latitude = latitude;
            Longitude = longitude;
            GpsAccuracy = gpsAccuracy;
            DataInterval = dataInterval;
            UnitValues = unitValues;
            Account = account;
            UnitType = unitType;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Latitude")]
        public double? Latitude { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Longitude")]
        public double? Longitude { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "GpsAccuracy")]
        public double? GpsAccuracy { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Minute', 'Minutes5',
        /// 'Seconds20Boost'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "DataInterval")]
        public string DataInterval { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "UnitValues")]
        public System.Collections.Generic.IList<WriteUnitValueDto> UnitValues { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Account")]
        public AccountIdDto Account { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "UnitType")]
        public UnitTypeIdDto UnitType { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (DataInterval == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "DataInterval");
            }
            if (this.UnitValues != null)
            {
                foreach (var element in this.UnitValues)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
            if (this.Account != null)
            {
                this.Account.Validate();
            }
            if (this.UnitType != null)
            {
                this.UnitType.Validate();
            }
        }
    }
}
