// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Remoni.API.DataAccess.Client.Models
{
    using System.Linq;

    /// <summary>
    /// ErrorDetailsResult
    /// </summary>
    public partial class FourZeroZeroError : ErrorDetailsResult
    {
        /// <summary>
        /// Initializes a new instance of the FourZeroZeroError class.
        /// </summary>
        public FourZeroZeroError() { }

        /// <summary>
        /// Initializes a new instance of the FourZeroZeroError class.
        /// </summary>
        public FourZeroZeroError(string code, string message, System.Collections.Generic.IList<BadRequestError> badRequestErrors = default(System.Collections.Generic.IList<BadRequestError>), System.Collections.Generic.IList<PropertyValueError> propertyValueErrors = default(System.Collections.Generic.IList<PropertyValueError>), System.Collections.Generic.IList<ArrayPropertyValueError> arrayPropertyValueErrors = default(System.Collections.Generic.IList<ArrayPropertyValueError>))
            : base(code, message, badRequestErrors, propertyValueErrors, arrayPropertyValueErrors)
        {
        }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public override void Validate()
        {
            base.Validate();
        }
    }
}
