// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Remoni.API.DataAccess.Client.Models
{
    using System.Linq;

    public partial class MultiPartFormFile
    {
        /// <summary>
        /// Initializes a new instance of the MultiPartFormFile class.
        /// </summary>
        public MultiPartFormFile() { }

        /// <summary>
        /// Initializes a new instance of the MultiPartFormFile class.
        /// </summary>
        public MultiPartFormFile(byte[] fileData = default(byte[]), string fileName = default(string))
        {
            FileData = fileData;
            FileName = fileName;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "FileData")]
        public byte[] FileData { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "FileName")]
        public string FileName { get; set; }

    }
}
