// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Remoni.API.DataAccess.Client.Models
{
    using System.Linq;

    public partial class ReadUnitTypeAlarmConfigurationDto
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ReadUnitTypeAlarmConfigurationDto class.
        /// </summary>
        public ReadUnitTypeAlarmConfigurationDto() { }

        /// <summary>
        /// Initializes a new instance of the
        /// ReadUnitTypeAlarmConfigurationDto class.
        /// </summary>
        /// <param name="type">Possible values include: 'Integer',
        /// 'Datetime'</param>
        public ReadUnitTypeAlarmConfigurationDto(string type, int alarmTypeId, string key = default(string))
        {
            Key = key;
            Type = type;
            AlarmTypeId = alarmTypeId;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Key")]
        public string Key { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Integer', 'Datetime'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "AlarmTypeId")]
        public int AlarmTypeId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Type == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Type");
            }
        }
    }
}
