// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Remoni.API.DataAccess.Client.Models
{
    using System.Linq;

    public partial class ReadUnitAlarmConfigurationDto
    {
        /// <summary>
        /// Initializes a new instance of the ReadUnitAlarmConfigurationDto
        /// class.
        /// </summary>
        public ReadUnitAlarmConfigurationDto() { }

        /// <summary>
        /// Initializes a new instance of the ReadUnitAlarmConfigurationDto
        /// class.
        /// </summary>
        /// <param name="type">Possible values include: 'Integer',
        /// 'Datetime'</param>
        public ReadUnitAlarmConfigurationDto(string type, int alarmTypeId, int unitId, string key = default(string), string value = default(string))
        {
            Key = key;
            Type = type;
            AlarmTypeId = alarmTypeId;
            UnitId = unitId;
            Value = value;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Key")]
        public string Key { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Integer', 'Datetime'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "AlarmTypeId")]
        public int AlarmTypeId { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "UnitId")]
        public int UnitId { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Value")]
        public string Value { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Type == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Type");
            }
        }
    }
}
