// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Remoni.API.DataAccess.Client.Models
{
    using System.Linq;

    public partial class ReadUnitTypeFieldDto
    {
        /// <summary>
        /// Initializes a new instance of the ReadUnitTypeFieldDto class.
        /// </summary>
        public ReadUnitTypeFieldDto() { }

        /// <summary>
        /// Initializes a new instance of the ReadUnitTypeFieldDto class.
        /// </summary>
        /// <param name="sensorType">Possible values include: 'AccessPoint',
        /// 'PowerMoniSpot', 'PowerMoniProC', 'FlowMoniSpot', 'FlowMoniPro',
        /// 'HeatMoniSpot', 'HeatMoniPro', 'TempMoniPro', 'RoomMoniSpot',
        /// 'RoomMoniPro', 'DataMoni'</param>
        public ReadUnitTypeFieldDto(int unitTypeFieldId, string name, string description = default(string), string sensorType = default(string))
        {
            UnitTypeFieldId = unitTypeFieldId;
            Description = description;
            Name = name;
            SensorType = sensorType;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "UnitTypeFieldId")]
        public int UnitTypeFieldId { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'AccessPoint',
        /// 'PowerMoniSpot', 'PowerMoniProC', 'FlowMoniSpot', 'FlowMoniPro',
        /// 'HeatMoniSpot', 'HeatMoniPro', 'TempMoniPro', 'RoomMoniSpot',
        /// 'RoomMoniPro', 'DataMoni'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "SensorType")]
        public string SensorType { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Name");
            }
        }
    }
}
