// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Remoni.API.DataAccess.Client.Models
{
    using System.Linq;

    public partial class ReadUserRolesDto
    {
        /// <summary>
        /// Initializes a new instance of the ReadUserRolesDto class.
        /// </summary>
        public ReadUserRolesDto() { }

        /// <summary>
        /// Initializes a new instance of the ReadUserRolesDto class.
        /// </summary>
        public ReadUserRolesDto(UserNoRefsDto user = default(UserNoRefsDto), System.Collections.Generic.IList<string> roles = default(System.Collections.Generic.IList<string>))
        {
            User = user;
            Roles = roles;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "User")]
        public UserNoRefsDto User { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Roles")]
        public System.Collections.Generic.IList<string> Roles { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (this.User != null)
            {
                this.User.Validate();
            }
        }
    }
}
