// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Remoni.API.DataAccess.Client.Models
{
    using System.Linq;

    public partial class SensorIdDto
    {
        /// <summary>
        /// Initializes a new instance of the SensorIdDto class.
        /// </summary>
        public SensorIdDto() { }

        /// <summary>
        /// Initializes a new instance of the SensorIdDto class.
        /// </summary>
        public SensorIdDto(int sensorId)
        {
            SensorId = sensorId;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "SensorId")]
        public int SensorId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
