// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Remoni.API.DataAccess.Client.Models
{
    using System.Linq;

    public partial class SensorActivitiesNoRefsDto
    {
        /// <summary>
        /// Initializes a new instance of the SensorActivitiesNoRefsDto class.
        /// </summary>
        public SensorActivitiesNoRefsDto() { }

        /// <summary>
        /// Initializes a new instance of the SensorActivitiesNoRefsDto class.
        /// </summary>
        public SensorActivitiesNoRefsDto(int sensorId, System.DateTimeOffset lastActivity, int? gatewayId = default(int?), int? receivedSignalStrengthIndication = default(int?), int? linkQualityIndication = default(int?))
        {
            SensorId = sensorId;
            GatewayId = gatewayId;
            LastActivity = lastActivity;
            ReceivedSignalStrengthIndication = receivedSignalStrengthIndication;
            LinkQualityIndication = linkQualityIndication;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "SensorId")]
        public int SensorId { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "GatewayId")]
        public int? GatewayId { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "LastActivity")]
        public System.DateTimeOffset LastActivity { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ReceivedSignalStrengthIndication")]
        public int? ReceivedSignalStrengthIndication { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "LinkQualityIndication")]
        public int? LinkQualityIndication { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
