// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Remoni.API.DataAccess.Client.Models
{
    using System.Linq;

    public partial class UnitTypeNoRefsDto
    {
        /// <summary>
        /// Initializes a new instance of the UnitTypeNoRefsDto class.
        /// </summary>
        public UnitTypeNoRefsDto() { }

        /// <summary>
        /// Initializes a new instance of the UnitTypeNoRefsDto class.
        /// </summary>
        public UnitTypeNoRefsDto(int unitTypeId, string name, string description = default(string))
        {
            UnitTypeId = unitTypeId;
            Name = name;
            Description = description;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "UnitTypeId")]
        public int UnitTypeId { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Description")]
        public string Description { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Name");
            }
        }
    }
}
