// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Remoni.API.DataAccess.Client.Models
{
    using System.Linq;

    public partial class UnitIdDto
    {
        /// <summary>
        /// Initializes a new instance of the UnitIdDto class.
        /// </summary>
        public UnitIdDto() { }

        /// <summary>
        /// Initializes a new instance of the UnitIdDto class.
        /// </summary>
        public UnitIdDto(int unitId)
        {
            UnitId = unitId;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "UnitId")]
        public int UnitId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
