// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Remoni.API.DataAccess.Client.Models
{
    using System.Linq;

    /// <summary>
    /// Defines headers for GetCollectionAsyncByqueryOptions operation.
    /// </summary>
    public partial class UnitsGetCollectionAsyncByqueryOptionsHeaders
    {
        /// <summary>
        /// Initializes a new instance of the
        /// UnitsGetCollectionAsyncByqueryOptionsHeaders class.
        /// </summary>
        public UnitsGetCollectionAsyncByqueryOptionsHeaders() { }

        /// <summary>
        /// Initializes a new instance of the
        /// UnitsGetCollectionAsyncByqueryOptionsHeaders class.
        /// </summary>
        /// <param name="link">Provides links to current, previous and next
        /// for Paged Responses. See the Query Options menu for more
        /// details.</param>
        /// <param name="xTotalCount">A Paged Response might only include some
        /// of the records. This provides the total number of records that
        /// exists.</param>
        public UnitsGetCollectionAsyncByqueryOptionsHeaders(string link = default(string), int? xTotalCount = default(int?))
        {
            Link = link;
            XTotalCount = xTotalCount;
        }

        /// <summary>
        /// Gets or sets provides links to current, previous and next for
        /// Paged Responses. See the Query Options menu for more details.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Link")]
        public string Link { get; set; }

        /// <summary>
        /// Gets or sets a Paged Response might only include some of the
        /// records. This provides the total number of records that exists.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "X-Total-Count")]
        public int? XTotalCount { get; set; }

    }
}
