// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Remoni.API.DataAccess.Client.Models
{
    using System.Linq;

    public partial class WriteAlarmUserNoteDto
    {
        /// <summary>
        /// Initializes a new instance of the WriteAlarmUserNoteDto class.
        /// </summary>
        public WriteAlarmUserNoteDto() { }

        /// <summary>
        /// Initializes a new instance of the WriteAlarmUserNoteDto class.
        /// </summary>
        public WriteAlarmUserNoteDto(AlarmSubtypeIdDto alarmSubtype, UnitIdDto unit, string message = default(string))
        {
            AlarmSubtype = alarmSubtype;
            Unit = unit;
            Message = message;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "AlarmSubtype")]
        public AlarmSubtypeIdDto AlarmSubtype { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Unit")]
        public UnitIdDto Unit { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Message")]
        public string Message { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (AlarmSubtype == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "AlarmSubtype");
            }
            if (Unit == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Unit");
            }
            if (this.AlarmSubtype != null)
            {
                this.AlarmSubtype.Validate();
            }
            if (this.Unit != null)
            {
                this.Unit.Validate();
            }
        }
    }
}
