// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Remoni.API.DataAccess.Client.Models
{
    using System.Linq;

    public partial class WriteUnitValueDto
    {
        /// <summary>
        /// Initializes a new instance of the WriteUnitValueDto class.
        /// </summary>
        public WriteUnitValueDto() { }

        /// <summary>
        /// Initializes a new instance of the WriteUnitValueDto class.
        /// </summary>
        public WriteUnitValueDto(int? index = default(int?), UnitTypeFieldIdDto unitTypeField = default(UnitTypeFieldIdDto), SensorIdDto sensor = default(SensorIdDto))
        {
            Index = index;
            UnitTypeField = unitTypeField;
            Sensor = sensor;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Index")]
        public int? Index { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "UnitTypeField")]
        public UnitTypeFieldIdDto UnitTypeField { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Sensor")]
        public SensorIdDto Sensor { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (this.UnitTypeField != null)
            {
                this.UnitTypeField.Validate();
            }
            if (this.Sensor != null)
            {
                this.Sensor.Validate();
            }
        }
    }
}
