// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Remoni.API.DataAccess.Client.Models
{
    using System.Linq;

    public partial class WriteUserRoleDto
    {
        /// <summary>
        /// Initializes a new instance of the WriteUserRoleDto class.
        /// </summary>
        public WriteUserRoleDto() { }

        /// <summary>
        /// Initializes a new instance of the WriteUserRoleDto class.
        /// </summary>
        /// <param name="role">Possible values include: 'Administrator',
        /// 'User', 'ReadOnly'</param>
        public WriteUserRoleDto(string username, string role)
        {
            Username = username;
            Role = role;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Username")]
        public string Username { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Administrator', 'User',
        /// 'ReadOnly'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Role")]
        public string Role { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Username == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Username");
            }
            if (Role == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Role");
            }
        }
    }
}
